apiVersion: v1
kind: Namespace
metadata:
  name: cloud-namespace
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: cloudru-deployment
  namespace: cloud-namespace
spec:
  replicas: 3
  selector:
    matchLabels:
      app: cloudru-app
  template:
    metadata:
      labels:
        app: cloudru-app  
    spec:
      containers:
      - name: cloudru-container
        image: dreshik/cloudru_app:latest
        args:
        - /bin/sh
        - -c
        - touch /tmp/healthy; sleep 30; rm -f /tmp/healthy; sleep 600
        imagePullPolicy: Always
        livenessProbe:
          exec:
            command:
            - cat
            - /tmp/healthy
          initialDelaySeconds: 20
          periodSeconds: 5
        readinessProbe:
          httpGet:
            scheme: HTTP
            path: /healthz
            port: 8000
          initialDelaySeconds: 20
          periodSeconds: 5
        env:
        - name: ID
          valueFrom:
            fieldRef:
              fieldPath: metadata.uid
---
apiVersion: v1
kind: Service
metadata:
  name: cloudru-service
  namespace: cloud-namespace
spec:
  selector:
    app: cloudru-app
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
  type: LoadBalancer  # Use 'ClusterIP' for an internal service